// Export pages
export 'login_signup/login_signup_widget.dart' show LoginSignupWidget;
export 'forget_password/forget_password_widget.dart' show ForgetPasswordWidget;
export 'home_page/home_page_widget.dart' show HomePageWidget;
export 'contac_list/contac_list_widget.dart' show ContacListWidget;
export 'add_contact/add_contact_widget.dart' show AddContactWidget;
export 'mydiary/mydiary_widget.dart' show MydiaryWidget;
export 'create_diary/create_diary_widget.dart' show CreateDiaryWidget;
export 'view_diary/view_diary_widget.dart' show ViewDiaryWidget;
export 'edit_diary/edit_diary_widget.dart' show EditDiaryWidget;
export 'information/information_widget.dart' show InformationWidget;
export 'information1/information1_widget.dart' show Information1Widget;
export 'information2/information2_widget.dart' show Information2Widget;
export 'information3/information3_widget.dart' show Information3Widget;
export 'information4/information4_widget.dart' show Information4Widget;
export 'information5/information5_widget.dart' show Information5Widget;
export 'profile/profile_widget.dart' show ProfileWidget;
export 'edit_profile/edit_profile_widget.dart' show EditProfileWidget;
export 'maincall/maincall_widget.dart' show MaincallWidget;
